mod acp_chat_commands;
mod agent_transcript_commands;
mod automation_commands;
mod browser_commands;
mod claude_commands;
mod clipboard_commands;
mod comfy_runtime_commands;
mod drama_commands;
mod dsh_commands;
pub(crate) mod dsh_workspace_sync;
mod filesystem_commands;
mod git_commands;
mod history_commands;
mod im_commands;
mod import_commands;
mod journal_commands;
mod launch_profile_commands;
mod layout_snapshot_commands;
mod local_history_commands;
mod mcp_config_commands;
mod media_commands;
mod memory_commands;
mod notification_commands;
mod orchestrator_commands;
mod performance_commands;
mod pi_rpc_commands;
mod plan_commands;
mod platform_commands;
mod process_commands;
mod project_commands;
mod project_hooks_commands;
mod project_skill_commands;
mod provider_commands;
mod quick_command_commands;
mod runner_commands;
mod screenshot_commands;
mod session_index_commands;
mod session_restore_commands;
mod settings_commands;
mod shared_mcp_commands;
mod skill_commands;
mod spec_commands;
mod ssh_file_commands;
mod ssh_machine_commands;
mod system_stats_commands;
mod tailscale_commands;
mod task_binding_commands;
mod task_queue_commands;
mod terminal_commands;
mod terminal_path_link_commands;
mod todo_commands;
mod usage_stats_commands;
mod voice_commands;
mod wallpaper_commands;
mod web_access_commands;
mod window_commands;
mod workspace_commands;
mod workspace_snapshot_commands;
mod worktree_commands;
mod wsl_commands;

pub use acp_chat_commands::*;
pub use agent_transcript_commands::*;
pub use automation_commands::*;
pub use browser_commands::*;
pub use claude_commands::*;
pub use clipboard_commands::*;
pub use comfy_runtime_commands::*;
pub use drama_commands::*;
pub use dsh_commands::*;
pub use filesystem_commands::*;
pub use git_commands::*;
pub use history_commands::*;
pub use im_commands::*;
pub use import_commands::*;
pub use journal_commands::*;
pub use launch_profile_commands::*;
pub use layout_snapshot_commands::*;
pub use local_history_commands::*;
pub use mcp_config_commands::*;
pub use media_commands::*;
pub use memory_commands::*;
pub use notification_commands::*;
pub use orchestrator_commands::*;
pub use performance_commands::*;
pub use pi_rpc_commands::*;
pub use plan_commands::*;
pub use platform_commands::*;
pub use process_commands::*;
pub use project_commands::*;
pub use project_hooks_commands::*;
pub use project_skill_commands::*;
pub use provider_commands::*;
pub use quick_command_commands::*;
pub use runner_commands::*;
pub use screenshot_commands::*;
pub use session_index_commands::*;
pub use session_restore_commands::*;
pub use settings_commands::*;
pub use shared_mcp_commands::*;
pub use skill_commands::*;
pub use spec_commands::*;
pub use ssh_file_commands::*;
pub use ssh_machine_commands::*;
pub use system_stats_commands::*;
pub use tailscale_commands::*;
pub use task_binding_commands::*;
pub use task_queue_commands::*;
pub use terminal_commands::*;
pub use terminal_path_link_commands::*;
pub use todo_commands::*;
pub use usage_stats_commands::*;
pub use voice_commands::*;
pub use wallpaper_commands::*;
pub use web_access_commands::*;
pub use window_commands::*;
pub use workspace_commands::*;
pub use workspace_snapshot_commands::*;
pub use worktree_commands::*;
pub use wsl_commands::*;
